on:
  push:

name: Building V8

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.distro }} / v8-${{ matrix.version }}

# V8 version from node-20: https://github.com/nodejs/node/blob/v20.x-staging-backport/deps/v8/include/v8-version.h

    strategy:
      fail-fast: false
      matrix:
        distro: [ 'centos-8', 'debian-11', 'debian-11-arm', 'debian-12-libcxx', 'alpine' ]
        version: [ '11.3.244.8' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          docker build --build-arg v8_version=${{ matrix.version }} ${{ matrix.distro }} -t mybuild

      - name: copy
        run: |
          docker run -d --name myrun mybuild
          docker cp myrun:/v8-${{ matrix.version }}-static.tar.xz .
          docker stop myrun
          mv v8-${{ matrix.version }}-static.tar.xz v8-${{ matrix.version }}-${{ matrix.distro }}.tar.xz

      - name: store
        uses: actions/upload-artifact@v4
        with:
          name: v8-${{ matrix.version }}-${{ matrix.distro }}
          path: v8-${{ matrix.version }}-${{ matrix.distro }}.tar.xz

  release:
    runs-on: ubuntu-latest
    name: Store binaries as GitHub release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts for deployment
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/v8-*.tar.xz
